# Diplomatura en Ciencia de Datos, Aprendizaje Automático y sus Aplicaciones
## Facultad de Matemática Astronomía Física y Computación
### Universidad Nacional de Córdoba
---

## Practico
## Análisis y Visualización de Datos

### 1. General
Se propone la elaboración de un informe que deberá apuntar a un público técnico, pero sin conocimientos específicos en el tema.

Durante este práctico vamos a trabajar sobre el [dataset](https://drive.google.com/file/d/1GG2ROEb03pKezOmKLjuGLReLAg0vw3fO/view?usp=sharing) que contiene transacciones financieras.

Esta tabla contiene los movimientos que componen la cuenta del cliente. Puede tratarse de movimientos de compras, débitos automáticos, cargos, o cualquier otro concepto que conforma la cuenta del cliente.

---
Las variables más importantes sobre las que trabaja el dataset son:

* DNI del titular del movimiento
* Moneda movimiento 
    - Moneda en la que se realizó la operación 
* Id comercio de movimiento
* Numero del cupon movimiento 
    - Número de cupón asignado a la operación
* Debito/Credito movimiento 
    - Identificación del impacto positivo o negativo de la operación en la cuenta del cliente
* Producto movimiento
* Codigo empresa Movimiento 
    - Identificación de la empresa a la que se asigna la operación
* Tipo producto Movimiento 
    - Identificación del tipo de producto asociado a la tarjeta con la cual se realizó la operación
* Plan Movimiento
* Fecha vto cupon Movimiento 
* Fecha presentacion Movimiento 
    - Fecha de presentación de la operación por parte del comercio.
* Fecha Cupon Movimiento 
    - Fecha en la que se realizó la operación 
* Fecha Carga Sistema Movimiento 
    - Fecha de Vencimiento del Resumen de Cuenta que contiene la operación
* Monto Movimiento 
    - Monto total por el que se impactó la operación
* Importe cuota movimiento 
    - Monto de cada cuota de la operación
* Interes movimiento 
    - Monto de Interés que tiene asignada la operación
* Cargo adm seguro movimiento
* Cargo otorgamiento movimiento
* Cargo seguro vida movimiento
* Cargo administrativo movimiento 
* Seleccionado_ng
* Tipo prestamo movimiento 
    - Si el movimiento es un préstamo indica qué tipo de préstamo se otrogó
* Codigo contable movimiento  
    - Código contable de la operación que indica el débito o crédito al Titular
* Local venta producto 
    - Si la operación es un Producto Naranja indica el local de venta del producto.
* Marca debito automatico 
    - Indica si la operación es un débito automático o no
* Fecha extraccion movimiento 
    - Indica la Fecha de la extracción del file
* Id comercio otras marcas movimiento
* Documento id persona
* Fecha nacimiento
* estado civil
* sexo
* pais
* provincia
* ciudad
* domicilio codigo postal
* domicilio barrio

---

### 2. Análisis Inicial
Se propone que realicen un análisis estadístico de variables que seleccionen por ser de su interés o porque crean que son relevantes, dentro de las cuales tiene que estar `monto_compra_movimiento` y `producto_movimiento`. 
Deberán responder preguntas como:

* Qué tipo de variable es cada una?
* Existen outliers en las variables seleccionadas?
* Cómo es la frecuencia de las variables categóricas (Ejm `producto_movimiento`) que seleccionaron?
* Cómo es la distribución de las variables `monto_compra_movimiento` para cada `producto_movimiento` en el dataset? Se distribuye de manera normal?
* Cómo es la distribución de `monto_compra_movimiento` condicionada a otra variable?
* Entre qué variables de las seleccionadas existe más correlación?
* Como se distribuyen los productos en funcion al tipo de modena?

Descripcion de los productos/movimientos

| PRODUCTO |   DESCRIPCION            |
| :- | :----------------------------: |
| AV |  Revista Convivimos            |
| AX |	American Express              |
| CE |	Costo Traslado Vto.EE         |
| CP |	Costo Traslado Vto.PP         |
| EE |	Efectivo Expresso             |
| EG |	Efectivo Galicia              |
| EI |	Extracc.Cajeros Internac.     |
| EX |	Extracc.Cajeros Nac.          |
| MC |	MasterCard                    |
| MO |	Naranja MO                    |
| PC |	Plan de Cuotas                |
| PG |	Prestamos Galicia             |
| PL |	Plan Largo Com. Amigos        |
| PL |	Plan Largo                    |
| PM |	Plan de Pago Mostrador        |
| PN |	Prestamos Personales PN       |
| PP |	Plan de Pago Propuesto        |
| PR |	Prestamos Personales          |
| SD |	Sin Datos                     |
| SM |	Mensajes de texto a celulares |
| TA |	Transfer Naranja Arg.         |
| TC |	Tarjetas Telef.Control        |
| TE |	Transfer Naranja Ext.         |
| TG |	Tarjetas Telefonicas GEO      |
| VE |	Venta de Entradas             |
| VI |	Visa                          |
| VT |	Cargo Vtas.Telefon. Fila      |
| ZE |	Zeta Optada                   |


### 3. Análisis Estadístico 
* Qué producto/s movimiento están en todas o casi todas las provincias?
* Como se ditribuyen los montos para los productos anteriores acorde a la provincia? Que conclusiones podemos sacar de esto?
* Qué tipos de productos tiene los montos entre los más altos? En qué provincia se encuentran mayoritariamente?
* Qué tipos de productos tiene los montos entre los más baratos? En qué provincia se encuentran mayoritariamente?
* Los montos y productos están relacionados a la edad de las personas?
* Los montos y productos están relacionados a la antiguedad de la cuenta de las personas?
* Hay valores faltantes? Es mejor descartarlos o completarlos con un valor particular?
* Para el o los clientes que tienen movimientos en todos o casi todos los meses cúal es la tendencia en cuanto a los montos de cada producto?

### 4. Opcional
* Teniendo en cuenta el producto con mayor cantidad de movimientos, cual es la tasa "mensual" de `monto_compra_movimiento`
  - Hint: Percentage change between the current and a prior element [doc](https://pandas.pydata.org/docs/reference/api/pandas.DataFrame.pct_change.html).
* Son variables independientes las provincias, localidades y barrios a los montos?
* Es posible eliminar el factor de la inflacion en los productos?



Fecha de Entrega ~ 06/06

## Configuracion 
---
importado de librerias

In [1]:
import sys
from io import StringIO
import pandas as pd
if 'requests' not in sys.modules:
    !pip install 'requests'
import requests

import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
import numpy as np

Requirement already satisfied: requests in /home/sergio/.cache/pypoetry/virtualenvs/analisisyvisualizacion-Awt5-uqn-py3.9/lib/python3.9/site-packages (2.25.1)
Requirement already satisfied: certifi>=2017.4.17 in /home/sergio/.cache/pypoetry/virtualenvs/analisisyvisualizacion-Awt5-uqn-py3.9/lib/python3.9/site-packages (from requests) (2020.12.5)
Requirement already satisfied: idna<3,>=2.5 in /home/sergio/.cache/pypoetry/virtualenvs/analisisyvisualizacion-Awt5-uqn-py3.9/lib/python3.9/site-packages (from requests) (2.10)
Requirement already satisfied: chardet<5,>=3.0.2 in /home/sergio/.cache/pypoetry/virtualenvs/analisisyvisualizacion-Awt5-uqn-py3.9/lib/python3.9/site-packages (from requests) (4.0.0)
Requirement already satisfied: urllib3<1.27,>=1.21.1 in /home/sergio/.cache/pypoetry/virtualenvs/analisisyvisualizacion-Awt5-uqn-py3.9/lib/python3.9/site-packages (from requests) (1.26.4)
WARNING: You are using pip version 20.3.1; however, version 21.1.1 is available.
You should consider upgrading via the '/home/sergio/.cache/pypoetry/virtualenvs/analisisyvisualizacion-Awt5-uqn-py3.9/bin/python -m pip install --upgrade pip' command.

In [2]:
# Configuracion de seaborn estilo de grafico y escalado
sns.set_context(context='talk', font_scale=1.2)
sns.set_style("darkgrid")

lectura desde Google Drive

In [3]:
# link del csv compartido 
# https://drive.google.com/file/d/1GG2ROEb03pKezOmKLjuGLReLAg0vw3fO/view?usp=sharing
# se toma solo el hash identificador
file_id = '1GG2ROEb03pKezOmKLjuGLReLAg0vw3fO'
dwn_url = f'https://drive.google.com/uc?export=download&id={file_id}'
url = requests.get(dwn_url).text
filename = StringIO(url)

In [4]:
df = pd.read_csv(filename)
df

,dni_titular_movimiento,moneda_movimiento,id_comercio_movimiento,numero_cupon_movimiento,debito_credito_movimiento,producto_movimiento,codigo_empresa_movimiento,tipo_producto_movimiento,plan_movimiento,fecha_vto_cupon_movimiento,...,documento_id_persona,antiguedad_de_la_cuenta,fecha_nacimiento,estado_civil,sexo,pais,provincia,ciudad,domicilio_codigo_postal,domicilio_barrio
0,0009bc2dcde18aed9f804282e10e87aa669,0,20099902,999990,0,PL,1,0,1,2020-09-10,...,0009bc2dcde18aed9f804282e10e87aa669,NaN,1986-03-26,1.0,1.0,Argentina,NEUQUEN,ZAPALA-CONFLU.COVUNCO,8340.0,ZAPALA
1,0009bc2dcde18aed9f804282e10e87aa669,0,71328938,987518,0,PL,1,3,1,2020-09-10,...,0009bc2dcde18aed9f804282e10e87aa669,NaN,1986-03-26,1.0,1.0,Argentina,NEUQUEN,ZAPALA-CONFLU.COVUNCO,8340.0,ZAPALA
2,0009bc2dcde18aed9f804282e10e87aa669,0,71332461,534139,0,PL,1,3,1,2020-09-10,...,0009bc2dcde18aed9f804282e10e87aa669,NaN,1986-03-26,1.0,1.0,Argentina,NEUQUEN,ZAPALA-CONFLU.COVUNCO,8340.0,ZAPALA
3,0009bc2dcde18aed9f804282e10e87aa669,0,71332461,618880,0,PL,1,3,1,2020-09-10,...,0009bc2dcde18aed9f804282e10e87aa669,NaN,1986-03-26,1.0,1.0,Argentina,NEUQUEN,ZAPALA-CONFLU.COVUNCO,8340.0,ZAPALA
4,0009bc2dcde18aed9f804282e10e87aa669,0,71332461,877055,0,PL,1,3,1,2020-09-10,...,0009bc2dcde18aed9f804282e10e87aa669,NaN,1986-03-26,1.0,1.0,Argentina,NEUQUEN,ZAPALA-CONFLU.COVUNCO,8340.0,ZAPALA
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
46312,000cc4c96b36ebee509531731ab3b5c2755,0,64111133,165946,0,PC,1,3,3,2021-03-10,...,000cc4c96b36ebee509531731ab3b5c2755,NaN,1972-11-19,3.0,2.0,Argentina,BUENOS AIRES,MAR DEL PLATA,7600.0,LAS HERAS
46313,000325709aec3c50413d6ea30f16205e263,0,10099058,1,1,PL,0,0,1,2021-03-10,...,000325709aec3c50413d6ea30f16205e263,NaN,1973-08-06,1.0,1.0,Argentina,BUENOS AIRES,25 DE MAYO,6660.0,PLAZA ESPAÃ±A
46314,000190c81ee107511f72f56e58ca3923057,0,20099804,291830,0,ZE,1,3,3,2021-03-10,...,000190c81ee107511f72f56e58ca3923057,NaN,1973-01-28,2.0,1.0,Argentina,CORDOBA,VILLA NUEVA,5903.0,GOLF
46315,0001b861d2f59a257ebb2145fe41268c680,0,20099804,119884,0,ZE,1,3,1,2021-03-10,...,0001b861d2f59a257ebb2145fe41268c680,NaN,1972-12-11,4.0,2.0,NaN,NaN,NaN,3500.0,CENTRO
46316,000d3414ca016703af2101af3a891d61742,0,20099804,422271,0,ZE,1,3,1,2021-03-10,...,000d3414ca016703af2101af3a891d61742,NaN,1973-07-01,1.0,1.0,Argentina,BUENOS AIRES,ITUZAINGO,1714.0,ITUZAINGO

In [5]:
df.shape

(46317, 37)

In [6]:
df.describe()

,moneda_movimiento,id_comercio_movimiento,numero_cupon_movimiento,debito_credito_movimiento,codigo_empresa_movimiento,tipo_producto_movimiento,plan_movimiento,monto_compra_movimiento,importe_cuota_movimiento,interes_movimiento,...,seleccionado_ng,codigo_contable_movimiento,local_venta_producto,marca_debito_automatico,fecha_extraccion_movimiento,id_comercio_otras_marcas_movimiento,antiguedad_de_la_cuenta,estado_civil,sexo,domicilio_codigo_postal
count,46317.000000,4.631700e+04,46317.000000,46317.000000,46317.000000,46317.000000,46317.000000,46317.000000,46317.000000,46317.000000,...,46317.0,46317.000000,4.631700e+04,46317.000000,0.0,4.631700e+04,5153.000000,46167.000000,46167.000000,45980.000000
mean,0.395989,2.518017e+08,400966.504825,0.055876,0.985362,4.923441,1.369713,1904.076870,1953.478250,63.616920,...,0.0,874.862923,2.512751e+08,0.179567,NaN,2.460121e+07,82.607801,1.795243,1.529209,4529.466420
std,0.995913,3.373213e+08,410172.484633,0.229684,0.120101,7.769399,1.476293,5682.631223,6083.513285,941.092186,...,0.0,846.731424,3.376378e+08,0.383830,NaN,7.484045e+07,65.648752,1.170063,0.499152,2055.566089
min,0.000000,1.009903e+07,0.000000,0.000000,0.000000,0.000000,1.000000,-147263.640000,-147263.520000,-40355.640000,...,0.0,7.000000,1.009903e+07,0.000000,NaN,0.000000e+00,1.000000,0.000000,1.000000,0.000000
25%,0.000000,2.009980e+07,5258.000000,0.000000,1.000000,0.000000,1.000000,69.200000,69.200000,0.000000,...,0.0,303.000000,2.009980e+07,0.000000,NaN,0.000000e+00,29.000000,1.000000,1.000000,3110.000000
50%,0.000000,1.001000e+08,202102.000000,0.000000,1.000000,3.000000,1.000000,301.290000,301.290000,0.000000,...,0.0,387.000000,1.001000e+08,0.000000,NaN,0.000000e+00,60.000000,2.000000,2.000000,4448.000000
75%,0.000000,5.470033e+08,899999.000000,0.000000,1.000000,3.000000,1.000000,1428.820000,1429.990000,0.000000,...,0.0,1639.000000,5.470033e+08,0.000000,NaN,0.000000e+00,115.000000,2.000000,2.000000,5521.000000
max,3.000000,9.911089e+08,999999.000000,1.000000,1.000000,42.000000,18.000000,181278.900000,186034.790000,59999.200000,...,0.0,3347.000000,9.911089e+08,1.000000,NaN,3.637856e+08,288.000000,7.000000,2.000000,9420.000000

valores unicos por cada columna

In [7]:
df.nunique()

dni_titular_movimiento                   829
moneda_movimiento                          3
id_comercio_movimiento                  3251
numero_cupon_movimiento                20611
debito_credito_movimiento                  2
producto_movimiento                       12
codigo_empresa_movimiento                  2
tipo_producto_movimiento                   6
plan_movimiento                           12
fecha_vto_cupon_movimiento                10
fecha_presentacion_movimiento            257
fecha_cupon_movimiento                   264
fecha_carga_sistema_movimiento           235
monto_compra_movimiento                19856
importe_cuota_movimiento               19938
interes_movimiento                      1085
cargo_adm_seguro_movimiento                1
cargo_otorgamiento_movimiento              1
cargo_seguro_vida_movimiento               1
cargo_administrativo_movimiento            1
seleccionado_ng                            1
tipo_prestamo_movimiento                   1
codigo_contable_movimiento               127
local_venta_producto                    3159
marca_debito_automatico                    2
fecha_extraccion_movimiento                0
id_comercio_otras_marcas_movimiento     2473
documento_id_persona                     829
antiguedad_de_la_cuenta                   73
fecha_nacimiento                         811
estado_civil                               8
sexo                                       2
pais                                       1
provincia                                 24
ciudad                                   325
domicilio_codigo_postal                  374
domicilio_barrio                         623
dtype: int64